name: null
favicon: null
layout_spectrum: 0.029697655700147152
typography_spectrum: 0.1328145912848413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8455165785271674
  lightness: 0.9864255427382886
  saturation: 0.5657772766426206
  rhythmicContrast: 0.44822425907477736
purpose: []
